In [1]:
import networkx as nx
from common import *
import matplotlib.pyplot as plt
import iterative
import ilp
import coloring
from pathlib import Path
import pandas as pd

In [2]:
def bench(solver, solver_args, path, max_count):
    prep = []
    for file_path in Path(path).iterdir():
        if file_path.is_file():
            df = pd.read_parquet(file_path)
            
            G = nx.from_pandas_edgelist(
                df, 
                source="source", 
                target="target", 
                edge_attr=None
            )
            
            mcn = len(solver(G, *solver_args))
            prep.append({"test" : file_path, "mcn": mcn})
        if max_count and len(prep) == max_count:
            break
    return pd.DataFrame(prep)

In [3]:
%%time
df = bench(coloring.minimum_clique_cover, ["greedy"], "../data/nm", 10)
df.describe()

CPU times: user 53.6 ms, sys: 6.84 ms, total: 60.5 ms
Wall time: 62.2 ms

             mcn
count  10.000000
mean   28.200000
std     9.930872
min    17.000000
25%    21.500000
50%    25.000000
75%    34.750000
max    48.000000

In [4]:
%%time
df = bench(coloring.minimum_clique_cover, ["vote"], "../data/nm", 10)
df.describe()

CPU times: user 53.3 ms, sys: 9 μs, total: 53.3 ms
Wall time: 54.3 ms

             mcn
count  10.000000
mean   29.300000
std    10.883729
min    16.000000
25%    22.500000
50%    26.500000
75%    34.500000
max    53.000000

In [5]:
%%time
df = bench(iterative.minimum_clique_cover, ["smallest"], "../data/nm", 10)
df.describe()

CPU times: user 30 s, sys: 13.5 ms, total: 30 s
Wall time: 30.1 s

             mcn
count  10.000000
mean   26.100000
std    10.959015
min    14.000000
25%    19.250000
50%    22.500000
75%    32.750000
max    49.000000

In [6]:
%%time
df = bench(iterative.minimum_clique_cover, ["biggest"], "../data/nm", 10)
df.describe()

CPU times: user 6min 34s, sys: 71.8 ms, total: 6min 34s
Wall time: 6min 36s

             mcn
count  10.000000
mean   24.700000
std    10.044899
min    13.000000
25%    18.250000
50%    22.000000
75%    31.000000
max    45.000000

In [7]:
%%time
df = bench(coloring.minimum_clique_cover, ["greedy"], "../data/nm", None)
df.describe()

CPU times: user 2min 11s, sys: 413 ms, total: 2min 11s
Wall time: 2min 12s

              mcn
count  874.000000
mean   263.805492
std    139.496948
min     10.000000
25%    148.000000
50%    261.000000
75%    381.000000
max    519.000000

In [8]:
%%time
df = bench(coloring.minimum_clique_cover, ["vote"], "../data/nm", None)
df.describe()

CPU times: user 2min 55s, sys: 202 ms, total: 2min 55s
Wall time: 2min 56s

              mcn
count  874.000000
mean   279.694508
std    151.781205
min     10.000000
25%    152.000000
50%    276.000000
75%    405.750000
max    613.000000

In [9]:
%%time
df = bench(coloring.minimum_clique_cover, ["greedy"], "../data/1k_sparse", None)
df.describe()

CPU times: user 1min, sys: 120 ms, total: 1min
Wall time: 1min 1s

              mcn
count  120.000000
mean   492.450000
std     14.767583
min    464.000000
25%    479.750000
50%    494.500000
75%    504.250000
max    517.000000

In [10]:
%%time
df = bench(coloring.minimum_clique_cover, ["vote"], "../data/1k_sparse", None)
df.describe()

CPU times: user 1min 19s, sys: 116 ms, total: 1min 19s
Wall time: 1min 19s

             mcn
count  120.00000
mean   503.52500
std     23.53969
min    467.00000
25%    485.00000
50%    501.50000
75%    520.00000
max    574.00000